### ISSUE TITLE
Heroku Log showing error and crashed

### ISSUE THREAD

**Issue by rockzy77** [ZauteKm/GroupMusicBot-v2#3]
2021-06-21T06:52:55.372722+00:00 app[worker.1]: Traceback (most recent call last):
2021-06-21T06:52:55.372729+00:00 app[worker.1]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2021-06-21T06:52:55.372734+00:00 app[worker.1]:     "__main__", mod_spec)
2021-06-21T06:52:55.372741+00:00 app[worker.1]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
2021-06-21T06:52:55.372742+00:00 app[worker.1]:     exec(code, run_globals)
2021-06-21T06:52:55.372742+00:00 app[worker.1]:   File "/app/MusicBot/__main__.py", line 38, in <module>
2021-06-21T06:52:55.372747+00:00 app[worker.1]:     run()
2021-06-21T06:52:55.372750+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/dist-packages/pytgcalls/pytgcalls.py", line 186, in run
2021-06-21T06:52:55.372751+00:00 app[worker.1]:     self._app.start()
2021-06-21T06:52:55.372751+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/dist-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2021-06-21T06:52:55.372752+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2021-06-21T06:52:55.372752+00:00 app[worker.1]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
2021-06-21T06:52:55.372752+00:00 app[worker.1]:     return future.result()
2021-06-21T06:52:55.372753+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/utilities/start.py", line 53, in start
2021-06-21T06:52:55.372753+00:00 app[worker.1]:     is_authorized = await self.connect()
2021-06-21T06:52:55.372754+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/dist-packages/pyrogram/methods/auth/connect.py", line 39, in connect
2021-06-21T06:52:55.372754+00:00 app[worker.1]:     await self.load_session()
2021-06-21T06:52:55.372754+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/dist-packages/pyrogram/client.py", line 669, in load_session
2021-06-21T06:52:55.372755+00:00 app[worker.1]:     await self.storage.open()
2021-06-21T06:52:55.372755+00:00 app[worker.1]:   File "/usr/local/lib/python3.7/dist-packages/pyrogram/storage/memory_storage.py", line 41, in open
2021-06-21T06:52:55.372755+00:00 app[worker.1]:     self.name + "=" * (-len(self.name) % 4)
2021-06-21T06:52:55.372756+00:00 app[worker.1]: struct.error: unpack requires a buffer of 263 bytes

what to do
I placed all the config vars correctly

**Comment by roobini-gamer** [comment]
same

**Comment by kishannn07** [comment]
> same

Use new api and string session along with new bot token problem solved
